### ISSUE TITLE
V2 Authentication and V3 Authentication in iOS

### ISSUE THREAD

**Issue by Fonta1n3** [AnarchoTechNYC/meta#36]
Hey love your guides! Just wanted to point out that thanks to iCepa I have a working V2 password authentication in my app [Fully Noded](https://github.com/Fonta1n3/FullyNoded) and V3 authorized_client auth too. Its open sourced so please point people to it if they want to see how: 
[TorClient.swift](https://github.com/Fonta1n3/FullyNoded/blob/master/BitSense/Helpers/New%20Group/TorClient.swift)

**Comment by meitar** [comment]
If I'm understanding your comment correctly, in order for someone to use iCepa in a manner such that they can connect to an authenticated Onion service, they need to write Swift code and include it in an application that they then build and use. Is that correct?

If so, while it's certainly nice that this is possible, that's not a generic enough capability to warrant a mention in the existing guides that we maintain. If I'm mistaken, please help me understand how iCepa makes it possible for any app on an Apple iOS device to make use of an end-user supplied Onion service authentication credential so that we can add those instructions to our guides.

Also, as an aside and a suggestion for your own code, consider the possibility that you may want to use the [Tor control protocol](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt) if possible rather than writing authentication credentials to disk in a `torrc` file programmatically in order to load the credentials for your Onion service in your Tor client.

Thanks!
